on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  tmchuynhme:
    runs-on: ubuntu-latest
    steps:
      - name: article
        uses: actions/checkout@main
